/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MusicRouteImport } from './routes/music'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrderTokenRouteImport } from './routes/order.$token'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'
import { Route as ApiPaypalReturnRouteImport } from './routes/api/paypal/return'
import { Route as ApiPaypalCheckoutRouteImport } from './routes/api/paypal/checkout'
import { Route as ApiDownloadTokenRouteImport } from './routes/api/download.$token'

const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderTokenRoute = OrderTokenRouteImport.update({
  id: '/order/$token',
  path: '/order/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaypalReturnRoute = ApiPaypalReturnRouteImport.update({
  id: '/api/paypal/return',
  path: '/api/paypal/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaypalCheckoutRoute = ApiPaypalCheckoutRouteImport.update({
  id: '/api/paypal/checkout',
  path: '/api/paypal/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadTokenRoute = ApiDownloadTokenRouteImport.update({
  id: '/api/download/$token',
  path: '/api/download/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/music': typeof MusicRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/order/$token': typeof OrderTokenRoute
  '/api/download/$token': typeof ApiDownloadTokenRoute
  '/api/paypal/checkout': typeof ApiPaypalCheckoutRoute
  '/api/paypal/return': typeof ApiPaypalReturnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/music': typeof MusicRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/order/$token': typeof OrderTokenRoute
  '/api/download/$token': typeof ApiDownloadTokenRoute
  '/api/paypal/checkout': typeof ApiPaypalCheckoutRoute
  '/api/paypal/return': typeof ApiPaypalReturnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/music': typeof MusicRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/order/$token': typeof OrderTokenRoute
  '/api/download/$token': typeof ApiDownloadTokenRoute
  '/api/paypal/checkout': typeof ApiPaypalCheckoutRoute
  '/api/paypal/return': typeof ApiPaypalReturnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/music'
    | '/api/checkout'
    | '/order/$token'
    | '/api/download/$token'
    | '/api/paypal/checkout'
    | '/api/paypal/return'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/music'
    | '/api/checkout'
    | '/order/$token'
    | '/api/download/$token'
    | '/api/paypal/checkout'
    | '/api/paypal/return'
  id:
    | '__root__'
    | '/'
    | '/music'
    | '/api/checkout'
    | '/order/$token'
    | '/api/download/$token'
    | '/api/paypal/checkout'
    | '/api/paypal/return'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MusicRoute: typeof MusicRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  OrderTokenRoute: typeof OrderTokenRoute
  ApiDownloadTokenRoute: typeof ApiDownloadTokenRoute
  ApiPaypalCheckoutRoute: typeof ApiPaypalCheckoutRoute
  ApiPaypalReturnRoute: typeof ApiPaypalReturnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$token': {
      id: '/order/$token'
      path: '/order/$token'
      fullPath: '/order/$token'
      preLoaderRoute: typeof OrderTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paypal/return': {
      id: '/api/paypal/return'
      path: '/api/paypal/return'
      fullPath: '/api/paypal/return'
      preLoaderRoute: typeof ApiPaypalReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paypal/checkout': {
      id: '/api/paypal/checkout'
      path: '/api/paypal/checkout'
      fullPath: '/api/paypal/checkout'
      preLoaderRoute: typeof ApiPaypalCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download/$token': {
      id: '/api/download/$token'
      path: '/api/download/$token'
      fullPath: '/api/download/$token'
      preLoaderRoute: typeof ApiDownloadTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MusicRoute: MusicRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  OrderTokenRoute: OrderTokenRoute,
  ApiDownloadTokenRoute: ApiDownloadTokenRoute,
  ApiPaypalCheckoutRoute: ApiPaypalCheckoutRoute,
  ApiPaypalReturnRoute: ApiPaypalReturnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
